version: '3.8'

services:
  # Development Backend Service with hot reload
  vr-translate-backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: vr-translate-backend-dev
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9229:9229"  # Node.js debugger port
    environment:
      - NODE_ENV=development
      - PORT=8080
      - WEBSOCKET_PORT=8081
      - LOG_LEVEL=debug
      - DEBUG_MODE=true
      - MOCK_SERVICES=true
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      - /app/node_modules  # Prevent overwriting node_modules
      # Mount config
      - ./backend/config/local.json:/app/config/local.json:ro
    networks:
      - vr-translate-dev-network
    command: npm run dev

  # Redis for development
  redis-dev:
    image: redis:7-alpine
    container_name: vr-translate-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - vr-translate-dev-network

networks:
  vr-translate-dev-network:
    driver: bridge